added session 4 Homework
Kielv2/ASPNetCoreMasters pull request #3
Opened 2021-09-22 05:08 UTC by Kielv2

Hi :)

2021-09-22 05:41 UTC, jegtugado commented
Not a full review but a quick recommendation is to add [Route("{controller}")] to the ItemsController and remove the /items/ from the action routes. This approach was shown during session 3. ex: "/items/{itemId}" will become "{itemId}" only. This will make sure that the controller name will be a prefix on every route. Current implementation works but is not desirable

2021-09-23 09:12 UTC, jegtugado requested changes
Other than the notes in the comments, for me this PR looks good. Thanks for not following what I mentioned in the previous session for [Route("{controller}"] when it should be [Route("[controller]")]. Nice catch!

2021-09-23 09:12 UTC, jegtugado commented on ASPNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpPost("{itemcreatemodel}")]
For model binding to occur there is no need to indicate this on the route. We only want primitive types such as int, double, etc if we want to use this approach. Kindly remove the route template and change to [HttpPost] or [HttpPost("")]

2021-09-23 09:12 UTC, jegtugado commented on ASPNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpGet("GetByFilters")]
currently this action will work with the uri "/items/GetByFilters" but we want "/items/filterBy" as per requirements. Minor change needed

2021-09-24 17:37 UTC, kevinatgithub approved these changes

2021-09-27 16:25 UTC, jegtugado approved these changes

2021-09-27 16:25 UTC, merged