added session 7 homework.
Kielv2/ASPNetCoreMasters pull request #6
Opened 2021-10-11 10:04 UTC by Kielv2

2021-10-13 05:26 UTC, jegtugado requested changes
minor changes needed

2021-10-13 05:26 UTC, jegtugado commented on ASPNetCoreMasters/Filters/EnsureItemIdExistFilter.cs
> +            var itemId = (int)context.ActionArguments["itemId"];
Hi sir, we need to handle the scenario when there is no itemId argument to the action method so that the app will not encounter an error since we are applying this on the controller scope

2021-10-13 05:26 UTC, jegtugado commented on ASPNetCoreMasters/Filters/ExecutionTimeFilter.cs
> +            context.HttpContext.Items["StartTime"] = DateTime.UtcNow;
sir why is the value being set again to DateTime.UtcNow?

2021-10-14 07:48 UTC, Kielv2 commented on ASPNetCoreMasters/Filters/ExecutionTimeFilter.cs
> +            context.HttpContext.Items["StartTime"] = DateTime.UtcNow;
updated the code sir. thanks

2021-10-14 07:49 UTC, jegtugado approved these changes

2021-10-14 07:50 UTC, merged